[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["./dist/client/index.html", "./dist/server/entry-server.js"]

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/server"
  status = 200
  force = true