[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "zisi"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200